# Generated by Django 3.0.7 on 2020-09-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.IntegerField()),
                ('prix', models.IntegerField()),
                ('nb_chambres', models.IntegerField()),
                ('commune', models.CharField(max_length=100)),
                ('lien', models.CharField(max_length=300)),
            ],
        ),
    ]
