# Generated by Django 3.0.7 on 2020-10-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartement',
            name='lien',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
