# Generated by Django 3.0.7 on 2020-10-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartements', '0002_auto_20201001_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='immoID',
            field=models.IntegerField(default=0),
        ),
    ]
