# Generated by Django 3.0.7 on 2020-10-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartements', '0003_appartement_immoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartement',
            name='prix',
            field=models.IntegerField(choices=[(400, '< 400'), (600, '400 -> 600'), (1400, '600+ -> 1400')]),
        ),
    ]
