# Generated by Django 3.0.7 on 2020-10-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartements', '0004_auto_20201010_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='zimmoID',
            field=models.CharField(default='empty', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appartement',
            name='prix',
            field=models.IntegerField(choices=[(300, '< 300€'), (450, '< 450€'), (600, '< 600€'), (900, '< 900€'), (1400, '< 1400€'), (1800, '< 1800€')]),
        ),
    ]
