# Generated by Django 3.0.7 on 2020-10-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartements', '0005_auto_20201023_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appartement',
            name='immoID',
        ),
        migrations.RemoveField(
            model_name='appartement',
            name='zimmoID',
        ),
        migrations.AddField(
            model_name='appartement',
            name='generalID',
            field=models.CharField(default='empty', max_length=100),
            preserve_default=False,
        ),
    ]
